### ISSUE TITLE
Webrtc streaming bandwidth cost

### ISSUE THREAD

**Issue by okpatil4u** [GleasonK/SimpleRTC#2]
Hi there,

What would be bandwidth cost for the streamer ? How many viewers could join the broadcast ?

**Comment by GleasonK** [comment]
WebRTC alone is only P2P. Meaning that if you wanted a group chat between users A, B and C the following streams would be open:

```
A <--> B
A <--> C
B <--> C
```

In a streaming situation where A is streaming to B, C, and D, there is a large overhead for A:

```
A <--> B
A <--> C
A <--> D
```

If you with to accomplish large group chats or streams, look into [WebRTC Media Servers](https://www.fiware.org/devguides/real-time-processing-of-media-streams/whats-webrtc-and-whats-a-media-server/)
